name: Build and deploy Storybook to Github Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out latest code from Github
        uses: actions/checkout@v3
      - run: npm ci
      - name: Lerna Bootstrap
        env:
          NPM_TOKEN: ${{ secrets.FONT_AWESOME_TOKEN }}
        run: npx lerna bootstrap
      - name: Lerna build
        run: npx lerna run build
      - name: Build Storybook
        run: npm run build-storybook
      - name: GH Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: storybook-static
